parameters:
    teapotio_forum.throttle_service.class: Teapotio\Base\ForumBundle\Service\ThrottleService
    teapotio.form.type.wysiwyg_textarea.class: Teapotio\ForumBundle\Form\Type\WysiwygTextareaType
    teapotio.form.transformer.html_purifier.class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
    teapotio.forum.url.use_board_id: false
    teapotio.forum.url.use_topic_id: true
    teapotio.forum.listener.request.class: Teapotio\ForumBundle\Listener\RequestListener

services:
    teapotio.forum.throttle:
        class: %teapotio_forum.throttle_service.class%
        arguments: [@service_container]
    teapotio.form.transformer.html_purifier:
        class: %teapotio.form.transformer.html_purifier.class%
        arguments: [@exercise_html_purifier.default]
    teapotio.form.type.wysiwyg_textarea:
        class: %teapotio.form.type.wysiwyg_textarea.class%
        arguments: [@teapotio.form.transformer.html_purifier]
        tags:
            - { name: form.type, alias: wysiwyg_textarea }
    teapotio.forum.listener.request:
        class: %teapotio.forum.listener.request.class%
        arguments: [@security.context, @teapotio.forum.board, @teapotio.forum.path]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest }
