TeapotioBaseUserBundle_login:
    pattern:   /login/
    defaults:  { _controller: TeapotioUserBundle:Security:login }
TeapotioBaseUserBundle_signup:
    pattern:   /signup/
    defaults:  { _controller: TeapotioUserBundle:Registration:signup }
TeapotioBaseUserBundle_forgotPassword:
    pattern:   /forgot-password/
    defaults:  { _controller: TeapotioUserBundle:Account:forgotPassword }
TeapotioBaseUserBundle_resetPassword:
    pattern:   /reset-password/
    defaults:  { _controller: TeapotioUserBundle:Account:resetPassword }
TeapotioBaseUserBundle_login_check:
    pattern:   /login-check/
TeapotioBaseUserBundle_logout:
    pattern:   /logout/
TeapotioBaseUserBundle_settings:
    pattern:   /u/{userSlug}-{userId}/settings/
    defaults: { _controller: TeapotioUserBundle:Profile:settings }
    requirements:
        userSlug: "[^\/]+"
        userId: \d+

TeapotioBaseUserBundle_profile:
    pattern:   /u/{userSlug}-{userId}/
    defaults: { _controller: TeapotioUserBundle:Profile:index }
    requirements:
        userSlug: "[^\/]+"
        userId: \d+

TeapotioBaseUserBundle_setDefaultImage:
    pattern: /u/{userSlug}-{userId}/set-image/{imageId}/
    defaults: { _controller: TeapotioUserBundle:User:setDefaultImage }
    requirements:
        userSlug: "[^\/]+"
        userId: \d+

TeapotioBaseUserBundle_addImage:
    pattern: /u/{userSlug}-{userId}/add-image/
    defaults: { _controller: TeapotioUserBundle:User:addImage }
    requirements:
        _method: POST
        userSlug: "[^\/]+"
        userId: \d+

TeapotioBaseUserBundle_setDescription:
    pattern: /u/{userSlug}-{userId}/set-description/
    defaults: { _controller: TeapotioUserBundle:User:setDescription }
    requirements:
        _method: POST
        userSlug: "[^\/]+"
        userId: \d+

TeapotioBaseUserBundle_setSettings:
    pattern: /u/{userSlug}-{userId}/set-settings/
    defaults: { _controller: TeapotioUserBundle:User:setSettings }
    requirements:
        _method: POST
        userSlug: "[^\/]+"
        userId: \d+

TeapotioBaseUserBundle_setGroups:
    pattern: /u/{userSlug}-{userId}/set-groups/
    defaults: { _controller: TeapotioUserBundle:User:setGroups }
    requirements:
        _method: POST
        userSlug: "[^\/]+"
        userId: \d+
