parameters:
   teapotio_image.image_service.class: Teapotio\ImageBundle\Service\ImageService
   teapotio_image.image_repository.class: Teapotio\ImageBundle\Repository\ImageRepository

services:
   teapotio.image:
       class: %teapotio_image.image_service.class%
       arguments: [@doctrine.orm.entity_manager, %teapotio_image.image_repository.class%, %kernel.root_dir%]
